SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE core_batch;
TRUNCATE TABLE core_issue;
TRUNCATE TABLE core_issuenote;
TRUNCATE TABLE core_language_titles;
TRUNCATE TABLE core_languagetext;
TRUNCATE TABLE core_loadbatchevent;
TRUNCATE TABLE core_marc;
TRUNCATE TABLE core_note;
TRUNCATE TABLE core_ocr;
TRUNCATE TABLE core_page;
TRUNCATE TABLE core_pagenote;
TRUNCATE TABLE core_place_titles;
TRUNCATE TABLE core_preceedingtitlelink;
TRUNCATE TABLE core_publicationdate;
TRUNCATE TABLE core_reel;
TRUNCATE TABLE core_relatedtitlelink;
TRUNCATE TABLE core_subject;
TRUNCATE TABLE core_subject_titles;
TRUNCATE TABLE core_title;
TRUNCATE TABLE core_title_newspaper_types;
TRUNCATE TABLE core_url;
SET FOREIGN_KEY_CHECKS = 1;