SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE ghnp.core_batch;
TRUNCATE TABLE ghnp.core_issue;
TRUNCATE TABLE ghnp.core_issuenote;
TRUNCATE TABLE ghnp.core_language_titles;
TRUNCATE TABLE ghnp.core_languagetext;
TRUNCATE TABLE ghnp.core_loadbatchevent;
TRUNCATE TABLE ghnp.core_marc;
TRUNCATE TABLE ghnp.core_note;
TRUNCATE TABLE ghnp.core_ocr;
TRUNCATE TABLE ghnp.core_page;
TRUNCATE TABLE ghnp.core_pagenote;
TRUNCATE TABLE ghnp.core_place_titles;
TRUNCATE TABLE ghnp.core_preceedingtitlelink;
TRUNCATE TABLE ghnp.core_publicationdate;
TRUNCATE TABLE ghnp.core_reel;
TRUNCATE TABLE ghnp.core_relatedtitlelink;
TRUNCATE TABLE ghnp.core_subject;
TRUNCATE TABLE ghnp.core_subject_titles;
TRUNCATE TABLE ghnp.core_title;
TRUNCATE TABLE ghnp.core_url;
SET FOREIGN_KEY_CHECKS = 1;