SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE chronam.core_batch;
TRUNCATE TABLE chronam.core_issue;
TRUNCATE TABLE chronam.core_issuenote;
TRUNCATE TABLE chronam.core_language_titles;
TRUNCATE TABLE chronam.core_languagetext;
TRUNCATE TABLE chronam.core_loadbatchevent;
TRUNCATE TABLE chronam.core_marc;
TRUNCATE TABLE chronam.core_note;
TRUNCATE TABLE chronam.core_ocr;
TRUNCATE TABLE chronam.core_page;
TRUNCATE TABLE chronam.core_pagenote;
TRUNCATE TABLE chronam.core_place_titles;
TRUNCATE TABLE chronam.core_preceedingtitlelink;
TRUNCATE TABLE chronam.core_publicationdate;
TRUNCATE TABLE chronam.core_relatedtitlelink;
TRUNCATE TABLE chronam.core_subject;
TRUNCATE TABLE chronam.core_subject_titles;
TRUNCATE TABLE chronam.core_title;
TRUNCATE TABLE chronam.core_url;
SET FOREIGN_KEY_CHECKS = 1;