UPDATE public.core_place SET region_id = 6 WHERE name = 'Georgia--Atlanta';
UPDATE public.core_place SET region_id = 5 WHERE name = 'Georgia--Augusta';
UPDATE public.core_place SET county = 'Fulton', region_id = 6 WHERE name = 'Georgia--Campbell--Fairburn';
UPDATE public.core_place SET county = 'Bartow', region_id = 1 WHERE name = 'Georgia--Cass--Cassville';
UPDATE public.core_place SET region_id = 3 WHERE name = 'Georgia--Doughtry--Albany';
UPDATE public.core_place SET county = 'Fayette', region_id = 2 WHERE name = 'Georgia--Fayette County--Fayetteville';
UPDATE public.core_place SET region_id = 3 WHERE name = 'Georgia--Fort Gaines';
UPDATE public.core_place SET region_id = 1 WHERE name = 'Georgia--Haberasham--Cornelia';
UPDATE public.core_place SET county = 'Muscogee', region_id = 2 WHERE name = 'Georgia--Muskogee--Columbus';
UPDATE public.core_place SET county = 'Effingham', region_id = 3 WHERE name = 'Georgia--Rincon';
UPDATE public.core_place SET county = 'Ware', region_id = 3 WHERE name = 'Georgia--Ruskin';
UPDATE public.core_place SET county = 'Chatham', region_id = 3 WHERE name = 'Georgia--Savannah';
UPDATE public.core_place SET county = 'Clarke', region_id = 1 WHERE name = 'Georgia--Winterville';
UPDATE public.core_place SET county = 'Clarke', region_id = 1 WHERE name = 'Georgia--Athens-Clarke--Athens';
UPDATE public.core_place SET county = 'Bibb', region_id = 4 WHERE name = 'Georgia--Bibb County--Macon';
UPDATE public.core_place SET county = 'DeKalb', region_id = 6 WHERE name = 'Georgia--De Kalb--Atlanta';
UPDATE public.core_place SET county = 'Haralson', region_id = 2 WHERE name = 'Georgia--Haralson County--Bremen';
UPDATE public.core_place SET county = 'Meriwether', region_id = 2 WHERE name = 'Georgia--Meriweather--Manchester';
UPDATE public.core_place SET county = 'Gordon', region_id = 1 WHERE name = 'Georgia--Gordon--Echota';